import type { Metadata } from "next";
import Breadcrumbs from "@/components/Breadcrumbs";
import CreateUserStoryMappingSession from "@/components/CreateUserStoryMappingSession";
import ToolFeedbackPanel from "@/components/ToolFeedbackPanel";
import { buildMetadata } from "@/lib/seo";

export const metadata: Metadata = buildMetadata({ title: "Free User Story Mapping Tool | Plan Releases Online", description: "Run a friendly, real-time User Story Mapping workshop with your team. Map activities, tasks, user stories, and release slices, then export a clear PDF.", keywords: ["user story mapping tool", "user story map online", "user story mapping template", "agile release planning"], canonical: "https://agiletoolhub.com/tools/user-story-mapping" });

export default function UserStoryMappingPage() {
  return <div className="mx-auto max-w-5xl px-4 py-10"><Breadcrumbs items={[{ label: "Tools", href: "/tools" }, { label: "User Story Mapping" }]} /><span className="text-xs font-semibold uppercase tracking-wide text-blue-600">Free tool · Live collaboration</span><h1 className="mt-2 text-4xl font-bold text-slate-950">User Story Mapping for distributed teams</h1><p className="mt-4 max-w-3xl text-lg text-slate-600">Turn a product journey into a shared map, slice it into releases, and give your team a practical plan they can use after the workshop.</p><div className="my-10 rounded-3xl border border-blue-200 bg-gradient-to-br from-blue-50 to-indigo-50 p-8 text-center shadow-sm"><p className="mx-auto mb-6 max-w-xl text-slate-700">No account required. Share one session link with product, UX, QA, engineering, and domain experts.</p><CreateUserStoryMappingSession /></div><div className="grid gap-5 md:grid-cols-3">{[["🗺️", "Map the journey", "Organize user activities and tasks from left to right."], ["✂️", "Slice releases", "Separate the smallest valuable stories for MVP, Release 2, and Later."], ["🤝", "Align the team", "Collaborate live, save the map, and export a clear PDF."]].map(([icon, title, description]) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="text-3xl">{icon}</div><h2 className="mt-4 font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></div>)}</div><ToolFeedbackPanel toolName="User Story Mapping" toolSlug="user-story-mapping" /></div>;
}
